services:
    blazor:
        build:
            context: .
            dockerfile: MediaNest.Web/Dockerfile
        container_name: medianest_blazor
        environment:
            - DOTNET_ENVIRONMENT=Docker
            - AssetsFolder=/app/Assets
        ports:
            - "5001:8080"
        volumes:
            #- ./Assets:/app/Assets
            - ${ASSETS_PATH}:/app/Assets
            - ./blazor-keys:/app/keys
        depends_on:
            - mongo
            - webapi

    webapi:
        build:
            context: .
            dockerfile: MediaNest.ApiService/Dockerfile
        container_name: medianest_webapi
        environment:
            - DOTNET_ENVIRONMENT=Docker
            - AssetsFolder=/app/Assets
        ports:
            - "5000:8080"
        volumes:
            - ${ASSETS_PATH}:/app/Assets
        depends_on:
            - mongo
   
    mongo:
        image: mongo:7
        container_name: MediaNest_Mongo
        restart: always
        ports:
            - "27018:27017"
        volumes:
            - mongo_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            - MONGO_INITDB_DATABASE=MediaNest

volumes:
  mongo_data:

